name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello!"
        name: Print greeting
      - name: Print goodbye
        run: echo "bye!"  
  
